version: '3'

networks:
  database:
    internal: true
  api:

services:
  yessir-postgres:
    container_name: yessir-postgres
    image: bitnami/postgresql:16.3.0-debian-12-r14
    environment:
      POSTGRES_DB: 'yessir'
      POSTGRES_USER: 'yessir'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_ROOT_HOST: '%'
    volumes:
      - './yessir-database/postgres:/bitnami/postgresql'
    networks:
      - database
    expose:
      - 5432
    restart: unless-stopped

  yessir-api:
    container_name: yessir-api
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/brunovitalino/yessir-api-image:latest
    environment:
      DATABASE_HOST: 'yessir-postgres'
    ports:
      - 8080:8080
    networks:
      - database
      - api
    restart: unless-stopped
    depends_on:
      - yessir-postgres
