server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: YesSir
  datasource:
    url: jdbc:postgresql://localhost:5437/yessir
    username: yessir
    password: 1234
  jpa:
    show_sql: false
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #hibernate:
    #  ddl-aut: update
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

#ACTUATOR
management:
  tracing:
    sampling:
      # All traces should be sent to latency analysis tool
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    enable:
      jvm: true
    export:
      prometheus:
        enabled: true
    distribution:
      sla:
        http:
          server:
            requests: "50ms,100ms,200ms,300ms"
      # For Exemplars to work we need histogram buckets
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: "yessir-api"
