server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/yessir
    username: yessir
    password: 1234
  jpa:
    show_sql: false
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #hibernate:
    #  ddl-aut: update
    properties:
      hibernate:
        format_sql: false
