server:
  port: 8080

spring:
  # DATABASE
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:yessir-db}:${DATABASE_PORT:5432}/yessir
    username: yessir
    password: 1234
  jpa:
    show_sql: false
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #hibernate:
    #  ddl-aut: update
    properties:
      hibernate:
        format_sql: false
  # CACHE
  data:
    redis:
      host: ${CACHE_HOST:yessir-cache}
      port: ${CACHE_PORT:6379}
      password:
      timeout: 15000
