server:
  port: 8080

spring:
  application:
    name: YesSir
  datasource:
    url: jdbc:postgresql://localhost:5437/yessir
    username: yessir
    password: 1234
  jpa:
    show_sql: true
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    #hibernate:
    #  ddl-aut: update
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
