version: '3'

services:
  yessir-postgres:
    container_name: yessir-postgres
    image: bitnami/postgresql:16.3.0-debian-12-r14
    environment:
      POSTGRES_DB: 'yessir'
      POSTGRES_USER: 'yessir'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_ROOT_HOST: '%'
    healthcheck:
      test: pg_isready
    volumes:
      - './postgres:/bitnami/postgresql'
    ports:
      - 5437:5432
    restart: unless-stopped
