version: '3.8'

services:
  yessir-postgres:
    container_name: yessir-postgres
    image: bitnami/postgresql:16.3.0-debian-12-r14
    environment:
      POSTGRES_DB: 'yessir'
      POSTGRES_USER: 'yessir'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_ROOT_HOST: '%'
      POSTGRESQL_FORCE_INITDB: 'yes'
    healthcheck:
      test: pg_isready
    #volumes:
    #  - './postgres2:/bitnami/postgresql'
    ports:
      - 5437:5432
    restart: unless-stopped

  yessir-postgres-test:
    container_name: yessir-postgres-test
    image: bitnami/postgresql:16.3.0-debian-12-r14
    environment:
      POSTGRES_DB: 'yessir_test'
      POSTGRES_USER: 'yessir'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_RANDOM_ROOT_PASSWORD: 'yes'
      POSTGRES_ROOT_HOST: '%'
    healthcheck:
      test: pg_isready
    #volumes:
    #  - './postgres_test/data:/bitnami/postgresql/data'
    ports:
      - 5433:5432
    restart: unless-stopped

  yessir-cache:
    image: redis:7.0
    ports:
      - 6379:6379
