name: CI/CD Pipeline Desenvolvimento

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: yessir-cluster
  ECS_SERVICE: yessir-api-service
  CONTAINER_NAME: yessir-api-dev
  SONAR_PROJECT_NAME: YesSir_API_Dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: YesSir Environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # CI
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install SonarQube Scanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-linux-x64.zip
          unzip sonar-scanner.zip
          echo "SONNAR_SCANNER=$PWD/sonar-scanner-7.0.2.4839-linux-x64/bin" >> $GITHUB_ENV

      - name: Get Latest Tag Version
        id: get_tag_version
        run: |
          # Obter a última tag
          TAG_VERSION=$(git describe --tags --abbrev=0)
          echo "Última tag: $TAG_VERSION"

          # Definir como variável de ambiente
          echo "SONAR_PROJECT_VERSION=$TAG_VERSION" >> $GITHUB_ENV
